
####################################
######### Configure these ##########
####################################

# Use /login endpoint@KMS to get kms_access_key
# Alternatively use provided login script
# kms_access_key: "kms_access_key" 
kms_access_key: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTYyNTExMTAzNiwianRpIjoiN2MwZjhiNjgtZmM4OS00YjNjLTg2NDctMWExN2RhZmE0OThkIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IlVOUlJDIiwibmJmIjoxNjI1MTExMDM2fQ.Gsh9mW8gZI0BRqdwyUNkZVrC2qOOPTB2TpxSLA_pzFk" 


# uncomment the following when using basic authentication with the servers (KMS and backend)
# basic_auth:
#   user: VuRVk3wcgrFhxuuqagV3
#   pass: 5S86bYXtpumDEbNJpXeBghRPx4J5cxnWjuAp4RcK


kms:
  url: "http://192.168.1.101:5002"
backend_server:
  url: "http://192.168.1.101:5001"
  max_post_retries: 5

# max number of connections, 0=auto
web_conn_listen: 0

# number of encryption threads in worker pool
enc_worker_threads: 10


####################################
######## Encryption Policy #########
######### Configure these ##########
####################################

policy:

  #default, required , this specifies defaault encryption policy
  default:
    de_encrypt: False # optional, default false
    # The default ABE policy is required
    abe_pol: "default"

  index:
    full_index_overwrite: False # dont use any of the hardcoded indexes

    exact:
      - match: "ipv4"
      - match: "de"

    regex:
      - match: .*src.*



  timestamp: # optional but required for time range queries
    # timestamp is automatically encrypted using ORE
    # if any other encryption is desired, use the exact/regex matching mechanisms below
    # else they will also be encrypted using default CPABE only
    exact:
        - "time"
        - "timestamp"

    regex:
        - ".*time.*"
        - ".*timestamp.*"



  exact:
    - match: "time"
      de_encrypt: True
      abe_pol: "itops AND research"

    - match: "frequency"
      remove: True

    - match: "hours"
      de_encrypt: True
      abe_pol: "itops AND research"

      
    - match: "frequency2"
      de_encrypt: False
      abe_pol: "itops AND research"


  regex:
    - match: ".*time.*"
      abe_pol: "itops AND research"

    - match: ".*timestamp.*"
      abe_pol: "itops AND research"
    
    - match: ".*ssn.*"
      remove: True



####################################
########## Dev settings ############
####################################

debug: 
  # debug flag for information that does not fall under an specific debug flag below
  enabled: False
  # encrypt only one record and quit
  process_only_one: False
  # show encryption policy from the config file
  print_policy_config: False
  # print incoming record
  print_incoming_record: False
  # show what policy was applied to each field
  show_enc_policy: False
  # print fields names left before they are about to be encrytred by a encryption module
  print_left_keys: False
  # show resulting encrypted record, ready for posting
  print_encrypted_record: False
  # do not post data to backend server
  do_not_post_data: False
  # print whether it was posted or not
  print_was_posted: False

####################################
##### no need to change below ######
####################################


key_files:
  de: /secrets/de.bin
  ore: /secrets/ore.bin
  ore_params: /secrets/ore_params.bin
  cpabe_pub: /secrets/cpabe_pub.bin
  cpabe_secret: /secrets/cpabe_secret.bin
