debug: 
  enabled: False
  process_only_one: False
  
kms:
  url: "http://192.168.1.101:5002"
backend_server:
  url: "http://192.168.1.101:5001"
  max_post_retries: 5

key_files:
  de: /secrets/de.bin
  ore: /secrets/ore.bin
  cpabe_pub: /secrets/cpabe_pub.bin
  cpabe_secret: /secrets/cpabe_secret.bin

# name must not contain special characters like spaces, /
# alpha numeric only, -, _
name: "official_org_name" 

# api:
#   username: test_user1
#   token: ksyhfkjlashlkfjahsfa

policy:

  #default, required , this specifies defaault encryption policy
  default:
    de_encrypt: False # optional, default false
    # The default ABE policy is required
    abe_pol: "default"

  index:
    full_index_overwrite: False # dont use any of the hardcoded indexes

    exact:
      - match: "ipv4"

    regex:
      - match: .*src.*



  timestamp: # optional but required for time range queries
    # timestamp is automatically encrypted using ORE
    # if any other encryption is desired, use the exact/regex matching mechanisms below
    # else they will also be encrypted using default
    exact:
        - "time"
        - "timestamp"

    regex:
        - ".*time.*"
        - ".*timestamp.*"



  exact:
    - match: "time"
      de_encrypt: True
      abe_pol: "somerthign and something"

    - match: "frequency"
      remove: True

    - match: "hours"
      de_encrypt: True
      abe_pol: "somerthign and something"

      
    - match: "frequency2"
      de_encrypt: False
      abe_pol: "somerthign and something"


  regex:
    - match: ".*time.*"
      abe_pol: "somerthign and something"

    - match: ".*timestamp.*"
      abe_pol: "somerthign and something"
    
    - match: ".*something.*"
      remove: True