
####################################
######### Configure these ##########
####################################

# name must not contain special characters like spaces, /
# alpha numeric only, -, _
name: "official_org_name" 

# uncomment the following when usgin basic authentication with the server
# basic_auth:
#   user: test_user1
#   pass: ksyhfkjlashlkfjahsfa


kms:
  url: "http://192.168.1.101:5002"
backend_server:
  url: "http://192.168.1.101:5001"
  max_post_retries: 5

# max number of connections, 0=auto
web_conn_listen: 0

# number of encryption threads in worker pool
enc_worker_threads: 10


####################################
######## Encryption Policy #########
######### Configure these ##########
####################################

policy:

  #default, required , this specifies defaault encryption policy
  default:
    de_encrypt: False # optional, default false
    # The default ABE policy is required
    abe_pol: "default"

  index:
    full_index_overwrite: False # dont use any of the hardcoded indexes

    exact:
      - match: "de"

    regex:
      - match: .*src.*



  timestamp: # optional but required for time range queries
    # timestamp is automatically encrypted using ORE
    # if any other encryption is desired, use the exact/regex matching mechanisms below
    # else they will also be encrypted using default
    exact:
        - "time"
        - "timestamp"

    regex:
        - ".*time.*"
        - ".*timestamp.*"



  exact:
    - match: "time"
      de_encrypt: True
      abe_pol: "itops AND research"

    - match: "frequency"
      remove: True

    - match: "hours"
      de_encrypt: True
      abe_pol: "itops AND research"

      
    - match: "frequency2"
      de_encrypt: False
      abe_pol: "itops AND research"


  regex:
    - match: ".*time.*"
      abe_pol: "itops AND research"

    - match: ".*timestamp.*"
      abe_pol: "itops AND research"
    
    - match: ".*something.*"
      remove: True



####################################
########## Dev settings ############
####################################

debug: 
  enabled: False
  process_only_one: False
  show_enc_policy: False


####################################
##### no need to change below ######
####################################


key_files:
  de: /secrets/de.bin
  ore: /secrets/ore.bin
  cpabe_pub: /secrets/cpabe_pub.bin
  cpabe_secret: /secrets/cpabe_secret.bin